package com.biit.infographic.rest.api;

import com.biit.infographic.core.controllers.GeneratedInfographicController;
import com.biit.infographic.core.generators.PngGenerator;
import com.biit.infographic.core.models.GeneratedInfographicAsPngDTO;
import com.biit.infographic.core.models.svg.SvgTemplate;
import com.biit.infographic.core.pdf.PdfController;
import com.biit.infographic.core.providers.GeneratedInfographicProvider;
import com.biit.infographic.rest.api.model.InfographicSearch;
import com.biit.server.exceptions.NotFoundException;
import com.biit.server.rest.SecurityService;
import com.biit.server.utils.exceptions.EmptyPdfBodyException;
import com.biit.server.utils.exceptions.InvalidXmlElementException;
import com.biit.server.utils.zip.ZipContent;
import com.biit.server.utils.zip.ZipController;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.http.ContentDisposition;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

@RestController
@RequestMapping("/png")
public class PngServices extends ImageServices {

    private final GeneratedInfographicController generatedInfographicController;

    private final ZipController zipController;

    private final GeneratedInfographicProvider generatedInfographicProvider;

    private final PdfController pdfController;

    public PngServices(SecurityService securityService, GeneratedInfographicController generatedInfographicController,
                       ZipController zipController, GeneratedInfographicProvider generatedInfographicProvider,
                       PdfController pdfController) {
        super(securityService);
        this.generatedInfographicController = generatedInfographicController;
        this.zipController = zipController;
        this.generatedInfographicProvider = generatedInfographicProvider;
        this.pdfController = pdfController;
    }


    @PreAuthorize("hasAnyAuthority(@securityService.viewerPrivilege, @securityService.editorPrivilege, @securityService.adminPrivilege)")
    @Operation(summary = "Generates a PNG from a template", security = @SecurityRequirement(name = "bearerAuth"))
    @PostMapping(value = "/create", produces = {MediaType.APPLICATION_OCTET_STREAM_VALUE, MediaType.APPLICATION_JSON_VALUE},
            consumes = MediaType.APPLICATION_JSON_VALUE)
    public byte[] getAll(@RequestBody SvgTemplate svgTemplate, Authentication authentication, HttpServletResponse response,
                         HttpServletRequest request) {
        final ContentDisposition contentDisposition = ContentDisposition.builder("attachment")
                .filename("Infographic.png").build();
        response.setHeader(HttpHeaders.CONTENT_DISPOSITION, contentDisposition.toString());
        return PngGenerator.generate(svgTemplate);
    }

    @Operation(summary = "Search results as PNG generated by drools.", description = """
            - page: the PNG page if the infographic is composed by multiples PNGs.
            Parameters:
            - form: the form name.
            - version: the form version.
            - createdBy: who has filled up the form.
            - organization: which organization the form belongs to.
            - startDate: filtering forms from this day.
            - endDate: filtering facts to this day.
            """,
            security = @SecurityRequirement(name = "bearerAuth"))
    @PreAuthorize("hasAnyAuthority(@securityService.viewerPrivilege, @securityService.editorPrivilege, @securityService.adminPrivilege)")
    @ResponseStatus(value = HttpStatus.OK)
    @GetMapping(value = "/find/latest/{page}", produces = MediaType.APPLICATION_JSON_VALUE)
    public byte[] getLatest(
            @Parameter(name = "page", required = false) @PathVariable(value = "page", required = false) Integer page,
            HttpServletRequest httpRequest,
            @Parameter(name = "form", required = false) @RequestParam(value = "form", required = false) String form,
            @Parameter(name = "version", required = false) @RequestParam(value = "version", required = false) Integer version,
            @Parameter(name = "createdBy", required = false) @RequestParam(value = "createdBy", required = false) String createdBy,
            @Parameter(name = "organization", required = false) @RequestParam(value = "organization", required = false) Long organization,
            Authentication authentication, HttpServletRequest request) {
        if (createdBy == null) {
            createdBy = authentication.getName();
        }
        if (page == null) {
            page = 0;
        }
        canBeDoneForDifferentUsers(createdBy, authentication);

        final GeneratedInfographicAsPngDTO generatedInfographicAsPngDTO = GeneratedInfographicAsPngDTO
                .from(generatedInfographicController.findLatest(form, version, organization, createdBy));

        if (generatedInfographicAsPngDTO == null) {
            throw new NotFoundException(this.getClass(), "No infographic found!");
        }

        if (page >= generatedInfographicAsPngDTO.getContents().size()) {
            throw new NotFoundException(this.getClass(), "No page '" + page + "' exists. Maximum available pages are "
                    + generatedInfographicAsPngDTO.getContents().size() + ".");
        }

        return generatedInfographicAsPngDTO.getContents().get(page);
    }

    @Operation(summary = "Search results as PNG generated by drools.", description = """
            - page: the PNG page if the infographic is composed by multiples PNGs.
            Parameters:
            - form: the form name.
            - version: the form version.
            - createdBy: who has filled up the form.
            - organization: which organization the form belongs to.
            - startDate: filtering forms from this day.
            - endDate: filtering facts to this day.
            """,
            security = @SecurityRequirement(name = "bearerAuth"))
    @PreAuthorize("hasAnyAuthority(@securityService.viewerPrivilege, @securityService.editorPrivilege, @securityService.adminPrivilege)")
    @ResponseStatus(value = HttpStatus.OK)
    @GetMapping(value = "/find/latest/zip", produces = MediaType.APPLICATION_JSON_VALUE)
    public byte[] getLatestAsZip(
            @Parameter(name = "form", required = false) @RequestParam(value = "form", required = false) String form,
            @Parameter(name = "version", required = false) @RequestParam(value = "version", required = false) Integer version,
            @Parameter(name = "createdBy", required = false) @RequestParam(value = "createdBy", required = false) String createdBy,
            @Parameter(name = "organization", required = false) @RequestParam(value = "organization", required = false) Long organization,
            Authentication authentication, HttpServletRequest request, HttpServletResponse response) throws IOException {
        if (createdBy == null) {
            createdBy = authentication.getName();
        }
        canBeDoneForDifferentUsers(createdBy, authentication);

        final GeneratedInfographicAsPngDTO generatedInfographicAsPngDTO = GeneratedInfographicAsPngDTO
                .from(generatedInfographicController.findLatest(form, version, organization, createdBy));

        if (generatedInfographicAsPngDTO == null) {
            throw new NotFoundException(this.getClass(), "No infographic found!");
        }

        final ContentDisposition contentDisposition = ContentDisposition.builder("attachment")
                .filename((form != null ? form : "infographic") + ".zip").build();
        response.setHeader(HttpHeaders.CONTENT_DISPOSITION, contentDisposition.toString());
        final List<ZipContent> content = new ArrayList<>();
        int page = 1;
        for (byte[] image : generatedInfographicAsPngDTO.getContents()) {
            content.add(new ZipContent("Page_" + page, "png", image));
            page++;
        }
        return zipController.createZipData(content);
    }

    @Operation(summary = "Search results as PNG generated by drools.", description = """
            Parameters:
            - form: the form name.
            - version: the form version.
            - createdBy: who has filled up the form.
            - organization: which organization the form belongs to.
            - startDate: filtering forms from this day.
            - endDate: filtering facts to this day.
            """,
            security = @SecurityRequirement(name = "bearerAuth"))
    @PreAuthorize("hasAnyAuthority(@securityService.viewerPrivilege, @securityService.editorPrivilege, @securityService.adminPrivilege)")
    @ResponseStatus(value = HttpStatus.OK)
    @GetMapping(value = "/find/latest/pdf", produces = MediaType.APPLICATION_JSON_VALUE)
    public byte[] getLatestAsPdf(
            @Parameter(name = "form", required = false) @RequestParam(value = "form", required = false) String form,
            @Parameter(name = "version", required = false) @RequestParam(value = "version", required = false) Integer version,
            @Parameter(name = "createdBy", required = false) @RequestParam(value = "createdBy", required = false) String createdBy,
            @Parameter(name = "organization", required = false) @RequestParam(value = "organization", required = false) Long organization,
            Authentication authentication, HttpServletRequest request, HttpServletResponse response) throws InvalidXmlElementException,
            EmptyPdfBodyException {
        if (createdBy == null) {
            createdBy = authentication.getName();
        }
        canBeDoneForDifferentUsers(createdBy, authentication);

        final GeneratedInfographicAsPngDTO generatedInfographicAsPngDTO = GeneratedInfographicAsPngDTO
                .from(generatedInfographicController.findLatest(form, version, organization, createdBy));

        if (generatedInfographicAsPngDTO == null) {
            throw new NotFoundException(this.getClass(), "No infographic found!");
        }

        final ContentDisposition contentDisposition = ContentDisposition.builder("attachment")
                .filename((form != null ? form : "infographic") + ".pdf").build();
        response.setHeader(HttpHeaders.CONTENT_DISPOSITION, contentDisposition.toString());

        return pdfController.generatePdfFromImage(generatedInfographicAsPngDTO.getContents());
    }

    @Operation(summary = "Search results as a PDF generated by drools.", description = """
            Received a list of infographics, and the system puts together as one PDF document.
            Only the last version from each infographic is returned.
            """,
            security = @SecurityRequirement(name = "bearerAuth"))
    @PreAuthorize("hasAnyAuthority(@securityService.viewerPrivilege, @securityService.editorPrivilege, @securityService.adminPrivilege)")
    @ResponseStatus(value = HttpStatus.OK)
    @PostMapping(value = "/find/latest/pdf", produces = MediaType.APPLICATION_JSON_VALUE)
    public byte[] getAsPdf(
            @RequestBody List<InfographicSearch> infographicSearchs,
            Authentication authentication, HttpServletRequest request, HttpServletResponse response)
            throws InvalidXmlElementException, EmptyPdfBodyException {

        final ArrayList<byte[]> pngBitmaps = new ArrayList<>();

        for (InfographicSearch infographicSearch : infographicSearchs) {
            canBeDoneForDifferentUsers(infographicSearch.getCreatedBy(), authentication);
            final GeneratedInfographicAsPngDTO generatedInfographicAsPngDTO = GeneratedInfographicAsPngDTO
                    .from(generatedInfographicController
                            .findLatest(infographicSearch.getForm(), infographicSearch.getVersion(),
                                    infographicSearch.getOrganization(), infographicSearch.getCreatedBy()));

            pngBitmaps.addAll(generatedInfographicAsPngDTO.getContents());
        }

        if (pngBitmaps.isEmpty()) {
            throw new NotFoundException(this.getClass(), "No infographics found!");
        }

        final ContentDisposition contentDisposition = ContentDisposition.builder("attachment")
                .filename("infographic.pdf").build();
        response.setHeader(HttpHeaders.CONTENT_DISPOSITION, contentDisposition.toString());

        return pdfController.generatePdfFromImage(pngBitmaps);
    }
}
