package com.biit.infographic.rest.api;

import com.biit.infographic.core.controllers.GeneratedInfographicController;
import com.biit.infographic.core.generators.PngGenerator;
import com.biit.infographic.core.models.GeneratedInfographicAsPngDTO;
import com.biit.infographic.core.models.svg.SvgTemplate;
import com.biit.server.exceptions.NotFoundException;
import com.biit.server.rest.SecurityService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.http.ContentDisposition;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.server.MethodNotAllowedException;

import java.util.List;
import java.util.Objects;

@RestController
@RequestMapping("/png")
public class PngServices {

    private final SecurityService securityService;

    private final GeneratedInfographicController generatedInfographicController;

    public PngServices(SecurityService securityService, GeneratedInfographicController generatedInfographicController) {
        this.securityService = securityService;
        this.generatedInfographicController = generatedInfographicController;
    }

    protected void canBeDoneForDifferentUsers(String userName, Authentication authentication) {
        if (userName != null && !Objects.equals(userName, authentication.getName())) {
            final List<String> grantedAuthorities = authentication.getAuthorities().stream().map(GrantedAuthority::getAuthority).toList();
            if (!grantedAuthorities.contains(securityService.getAdminPrivilege()) && !grantedAuthorities.contains(this.securityService.getEditorPrivilege())) {
                throw new MethodNotAllowedException("You are not allowed to search information from other users.", null);
            }
        }
    }

    @PreAuthorize("hasAnyAuthority(@securityService.viewerPrivilege, @securityService.editorPrivilege, @securityService.adminPrivilege)")
    @Operation(summary = "Generates a PNG from a template", security = @SecurityRequirement(name = "bearerAuth"))
    @PostMapping(value = "/create", produces = {MediaType.APPLICATION_OCTET_STREAM_VALUE, MediaType.APPLICATION_JSON_VALUE},
            consumes = MediaType.APPLICATION_JSON_VALUE)
    public byte[] getAll(@RequestBody SvgTemplate svgTemplate, Authentication authentication, HttpServletResponse response,
                         HttpServletRequest request) {
        final ContentDisposition contentDisposition = ContentDisposition.builder("attachment")
                .filename("Infographic.png").build();
        response.setHeader(HttpHeaders.CONTENT_DISPOSITION, contentDisposition.toString());
        return PngGenerator.generate(svgTemplate);
    }

    @Operation(summary = "Search results as PNG generated by drools.", description = """
            - page: the PNG page if the infographic is composed by multiples PNGs.
            Parameters:
            - form: the form name.
            - version: the form version.
            - createdBy: who has filled up the form.
            - organization: which organization the form belongs to.
            - startDate: filtering forms from this day.
            - endDate: filtering facts to this day.
            """,
            security = @SecurityRequirement(name = "bearerAuth"))
    @PreAuthorize("hasAnyAuthority(@securityService.viewerPrivilege, @securityService.editorPrivilege, @securityService.adminPrivilege)")
    @ResponseStatus(value = HttpStatus.OK)
    @GetMapping(value = "/find/latest/{page}", produces = MediaType.APPLICATION_JSON_VALUE)
    public byte[] getLatest(
            @Parameter(name = "page", required = false) @PathVariable(value = "page", required = false) Integer page,
            HttpServletRequest httpRequest,
            @Parameter(name = "form", required = false) @RequestParam(value = "form", required = false) String form,
            @Parameter(name = "version", required = false) @RequestParam(value = "version", required = false) Integer version,
            @Parameter(name = "createdBy", required = false) @RequestParam(value = "createdBy", required = false) String createdBy,
            @Parameter(name = "organization", required = false) @RequestParam(value = "organization", required = false) Long organization,
            Authentication authentication, HttpServletRequest request) {
        if (createdBy == null) {
            createdBy = authentication.getName();
        }
        if (page == null) {
            page = 0;
        }
        canBeDoneForDifferentUsers(createdBy, authentication);

        final GeneratedInfographicAsPngDTO generatedInfographicAsPngDTO = GeneratedInfographicAsPngDTO
                .from(generatedInfographicController.findLatest(form, version, organization, createdBy));

        if (generatedInfographicAsPngDTO == null) {
            throw new NotFoundException(this.getClass(), "No infographic found!");
        }

        if (page >= generatedInfographicAsPngDTO.getPngContents().size()) {
            throw new NotFoundException(this.getClass(), "No page '" + page + "' exists. Maximum available pages are "
                    + generatedInfographicAsPngDTO.getPngContents().size() + ".");
        }

        return generatedInfographicAsPngDTO.getPngContents().get(page);
    }
}
